#!/usr/bin/env python3
from __future__ import annotations
import ast,hashlib,json,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parent
cm=json.loads((ROOT/'canonical_source_manifest.json').read_text())
src=ROOT/cm['source_filename']; ext=ROOT/cm['extractor_filename']; published=ROOT/cm['code_block_manifest_filename']
for p in (src,ext,published):
    if not p.exists(): raise SystemExit(f'missing mandatory publication input: {p.name}')
if hashlib.sha256(src.read_bytes()).hexdigest()!=cm['source_sha256']: raise SystemExit('canonical manuscript SHA-256 mismatch')
if hashlib.sha256(ext.read_bytes()).hexdigest()!=cm['extractor_sha256']: raise SystemExit('extractor SHA-256 mismatch')
with tempfile.TemporaryDirectory() as td:
    regenerated=Path(td)/'blocks.json'; subprocess.run([sys.executable,str(ext),str(src),str(regenerated)],check=True)
    if regenerated.read_bytes()!=published.read_bytes(): raise SystemExit('code-block manifest does not match deterministic extraction from canonical Markdown')
d=json.loads(published.read_text()); errors=[]
for b in d['blocks']:
    c=b['content']
    if hashlib.sha256(c.encode()).hexdigest()!=b['sha256']: errors.append(f"block {b['index']} content hash mismatch")
    if b['nonblank_lines']>=4 and not b['authenticity_label']: errors.append(f"block {b['index']} lacks authenticity label")
    if b['language'] in {'python','py'}:
        try: ast.parse(c)
        except SyntaxError as e: errors.append(f"block {b['index']} Python syntax: {e}")
joined='\n'.join(b['content'] for b in d['blocks'])
for stale in ('google.adk.workflows','nodes={','.diff.to_numpy()','risk-weighted unsafe rate','permissionDecision": "ask"'):
    if stale in joined: errors.append(f'forbidden stale interface or metric: {stale}')
if errors: raise SystemExit('\n'.join(errors))
print(f"OK: canonical source SHA verified; {len(d['blocks'])} blocks regenerated byte-for-byte; Python parsed and labels enforced")
